Update init script

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,7 +1,14 @@
 #!/usr/bin/env zsh
 
+if type git > /dev/null; then
+	echo "git not found. abort"
+	exit 1
+fi
+
 . .init.d/vim
 . .init.d/symlink
+. .init.d/tpm
+. .initd./zplug
 
 create_symlink $(cd $(dirname $0) && pwd)
 
